name: ERT-straight-release-snapshot

on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - release-snapshot
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Clone vhdl-ts-mode
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install binaries
        run: |
          test/test-hdl/scripts/vhdl/setup-env.sh
          test/test-hdl/scripts/vhdl/install-ts-grammar.sh

      - name: Run ERT tests
        run: |
          make
